spring:
  application:
    name: @pom.artifactId@

  cloud:
    config:
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig/
          search-paths: respo
      label: master


server:
  port: 8085

