spring:
  application:
    name: @pom.artifactId@

  cloud:
    config:
      server:
        git:
          uri: https://github.com/zysspace/SpringcloudConfig
          search-paths: respo
      label: master
#  rabbitmq:
#    host: 127.0.0.11
#    port: 5672
#    username: guest
#    password: guest


server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

management:
  endpoints:
    web:
      exposure:
        exclude: bus-refresh
